[build-system]
requires = ["setuptools>=45", "wheel"]
dependencies = ["seaborn>=0.11.0", "folium>=0.12.0", "matplotlib>=3.3.0", "scikit-learn>=1.0.0", "pandas>=1.5.0", "numpy>=1.23.0"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = ["pytest>=7.0.0", "black>=22.0.0", "isort>=5.0.0", "flake8>=4.0.0"]

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3